### PR TITLE
propagate tags to all resources

### LINKED ISSUE #922: VPC: Tags are not applied
### What happened?

When creating an AWSX VPC, tags are not applied to dependent resources.

### Steps to reproduce

```python
"""A Python Pulumi program"""

import pulumi_awsx as awsx

vpc = awsx.ec2.Vpc(
    "david-awsx-question",
    awsx.ec2.VpcArgs(
        subnet_specs=[
            awsx.ec2.SubnetSpecArgs(
                type=awsx.ec2.SubnetType.PUBLIC,
                tags={
                    "ingress": "HECK YEAH, BUDDY!",
                },
            ),
            awsx.ec2.SubnetSpecArgs(
                type=awsx.ec2.SubnetType.PRIVATE,
            ),
        ],
        tags={
            "createdby": "jkodroff",
        },
    )
)
```

### Expected Behavior

* `createdby` should (probably) be applied to all resources. It only seems to appear on the VPC itself.
* `ingress` should (definitely) be applied to the public subnets, and it is not.

### Actual Behavior

See above

### Output of `pulumi about`

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by jaxxstorm**
All resources should get the tags assigned to them.

In addition, I've added the subnet type to the route tables so we can differentiate them

Fixes #922

### CODE REVIEW

File: awsx/ec2/vpc.ts [hunk 1]
```diff
@@ -218,6 +223,7 @@ export class Vpc extends schema.Vpc<VpcData> {
                 allocationId: createEip ? eips[i].allocationId : allocationIds[i],
                 tags: {
                   Name: `${name}-${i + 1}`,
+                  ...args.tags,
```
Comment (danielrbradley) [inline awsx/ec2/vpc.ts:226]: This should be before the name to ensure Name doesn't get overwritten.

Comment (jaxxstorm) [reply awsx/ec2/vpc.ts:225]: Fixed!
