### PR TITLE
Re-order tag priority in ec2.Vpc

### LINKED ISSUE #967: If I set a `name` tag in the VPC component, use that instead of the resource name
### What happened?

```typescript
const vpc = new awsx.ec2.Vpc("vpc", {
    cidrBlock: "10.0.0.0/16",
    numberOfAvailabilityZones: 3,
    subnetSpecs: [{
        type: awsx.ec2.SubnetType.Public,
        name: "public",
    }],
    natGateways: {
        strategy: "None"
    },
    tags: {
        name: "my-vpc"
    }
});
```

If I have the above code for a new VPC, the component is setting the "name" tag to be the resource name (in the above case `vpc` rather than the name tag, `my-vpc`).

It happens here: https://github.com/pulumi/pulumi-awsx/blob/35614a308aac3dfa7e0c7f4cbc5d685c2b696580/awsx/ec2/vpc.ts#L92-L95

### Steps to reproduce

Use above code

### Expected Behavior

VPC should use the name tag to set the vpc name

### Actual Behavior

Component is overwriting the name tag with the resource name instead of what I'm providing

### Output of `pulumi about`

_No response_

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by peak-stephen**
Fixes #967, #985

As described in the above issues it's currently impossible to actually set the name of a VPC, for two different reasons.

This PR fixes both issues. I don't _think_ it will cause a regression that anybody notices, because right now setting a name causes creation of the VPC to fail.

---

A "nice to have" would be constructing the name tag of each subnet based on the name tag of the over all VPC, but that's a bigger change/feature so I'd rather treat this PR as simply a bug fix.

### CODE REVIEW

**Comment by danielrbradley** [comment]
Thanks for the contribution! I think this is all good but want to work through proving there's no risk of breaking changes here. Will follow up next week

File: awsx/ec2/vpc.ts [hunk 1]
```diff
@@ -161,7 +157,7 @@ export class Vpc extends schema.Vpc<VpcData> {
               mapPublicIpOnLaunch: spec.type.toLowerCase() === "public",
               cidrBlock: spec.cidrBlock,
               tags: {
-                ...args.tags,
```
Comment (danielrbradley) [inline awsx/ec2/vpc.ts:164]: This change has no impact on behaviour. The only difference between `args.tags` and `sharedTags` is adding a Name, but the name will always be overwritten below.

**Review by danielrbradley — APPROVED** [review]
Ok, worked through this in detail. I think the only way this could cause a breaking change is if anyone was accidentally passing a Name in their `args.tags` which would have previously been a no-op.

Therefore I'm happy for this to merge 👍

File: awsx/ec2/vpc.ts (hunk 1 above)
Comment (peak-stephen) [reply awsx/ec2/vpc.ts:164]: that's true, it was more for consistency/readability. No need to think about "why use `arg.tags` here instead of `sharedTags`
