### PR TITLE
fix: targetGroup errors appear in containerDefinition diff

### LINKED ISSUE #1248: Fargate service + LB target group handling includes exception in diff
### What happened?

When creating a minimal `awsx.ecs.FargateService` and passing in a target group from `awsx.lb.ApplicationLoadBalancer` in the `portMappings` arg, the "Calling [toJSON] on an [Output<T>] is not supported." exception shows up in the diff output.

Let me know if I'm doing something wrong.  Based on the types I think this is what the arg value should be for `targetGroup`, but the docs don't describe anything more about the inputs here.

### Example

Here is an MRE:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

export const clusterA = new aws.ecs.Cluster("cluster-a", {});

export const clusterA_serviceA_loadBalancer = new awsx.lb.ApplicationLoadBalancer(
  "cluster-a-service-a-lb",
  {},
);

export const clusterA_serviceA = new awsx.ecs.FargateService("cluster-a-service-a", {
  cluster: clusterA.arn,
  assignPublicIp: true,
  desiredCount: 1,
  taskDefinitionArgs: {
    container: {
      name: "cluster-a-service-a",
      image: "docker.io/nginx",
      cpu: 128,
      memory: 512,
      essential: true,
      portMappings: [
        {
          containerPort: 80,
          targetGroup: clusterA_serviceA_loadBalancer.defaultTargetGroup,
        },
      ],
    },
  },
});
```

Then run

    pulumi up

To get diff output (truncated):

```
Outputs:
  + clusterA                      : {
      + arn                   : output<string>
      + configuration         : output<string>
      + id                    : output<string>
      + name                  : "cluster-a-2d34c27"
      + serviceConnectDefaults: output<string>
      + settings              : output<string>
      + tags                  : output<string>
      + tagsAll               : output<string>
      + urn                   : "urn:pulumi:dev::pulumi_ecs_test::aws:ecs/cluster:Cluster::cluster-a"
    }
  + clusterA_serviceA             : {
      [...]
      + service                        : {
           [...]
        }
       [...]
      + taskDefinition                 : {
          + arn                    : output<string>
          + arnWithoutRevision     : output<string>
          + containerDefinitions   : (json) [
          +     [0]: {
                  [...]
                  + portMappings    : [
                  +     [0]: {
                          + containerPort: 80
                          + hostPort     : 80
                          + targetGroup  : {
                              + arn                           : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + arnSuffix                     : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + connectionTermination         : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + deregistrationDelay           : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + healthCheck                   : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + id                            : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + ipAddressType                 : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + lambdaMultiValueHeadersEnabled: "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + loadBalancingAlgorithmType    : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + loadBalancingCrossZoneEnabled : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + name                          : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + namePrefix                    : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + port                          : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + preserveClientIp              : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + protocol                      : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + protocolVersion               : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + proxyProtocolV2               : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + slowStart                     : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + stickiness                    : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + tags                          : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + tagsAll                       : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + targetFailovers               : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + targetHealthStates            : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + targetType                    : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + urn                           : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                              + vpcId                         : "Calling [toJSON] on an [Output<T>] is not supported.\n\nTo get the value of an Output as a JSON value or JSON string consider either:\n    1: o.apply(v => v.toJSON())\n    2: o.apply(v => JSON.stringify(v))\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of @pulumi/pulumi."
                            }
                        }
                    ]
                }
            ]

```

### Output of `pulumi about`

```
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  14.1.2
Arch     arm64

This project is written in nodejs: executable='/Users/[...]/.asdf/shims/node' version='v16.15.1'

[...]

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/[...]
User           [...]
Organizations  [...]
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/aws     6.28.1
@pulumi/awsx    2.6.0
@pulumi/pulumi  3.112.0
@types/node     18.19.26

Pulumi locates its logs in /var/folders/q3/mk2vg8h90lxdvblf8xs__w9c0000gq/T/ by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by corymhall**
The [container
definition](https://www.pulumi.com/registry/packages/aws/api-docs/ecs/taskdefinition/#containerdefinitions_nodejs) property of a Task Definition is a JSON string. We do not provide types for the container definition which means it is possible to include things in that JSON string that shouldn't be there. In the case of this bug, we are including an additional `targetGroup` object in the container definition string.

To fix this, I am removing the `targetGroup` field. 

fix #1248

### CODE REVIEW

File: awsx/ecs/fargateTaskDefinition.ts [hunk 1]
```diff
@@ -149,6 +149,7 @@ function buildTaskDefinitionArgs(
   if (mutableArgs.memory === undefined) {
     mutableArgs.memory = requiredMemoryAndCPU.memory;
   }
+
```
Comment (corymhall) [inline awsx/ecs/fargateTaskDefinition.ts:152]:
```suggestion
```

File: awsx/ecs/containers.ts [hunk 2]
```diff
@@ -101,7 +101,9 @@ export function getMappingInputs(
   tgPort: number | undefined,
 ): schema.TaskDefinitionPortMappingInputs {
   return {
-    ...mappingInput,
```
Comment (t0yv0) [inline awsx/ecs/containers.ts:104]: This makes me uneasy because schema.TaskDefinitionPortMappingInputs specified this schema:

```typescript
export interface TaskDefinitionPortMappingInputs {
    readonly appProtocol?: pulumi.Input<TaskDefinitionPortMappingAppProtocolInputs>;
    readonly containerPort?: pulumi.Input<number>;
    readonly containerPortRange?: pulumi.Input<string>;
    readonly hostPort?: pulumi.Input<number>;
    readonly name?: pulumi.Input<string>;
    readonly protocol?: pulumi.Input<string>;
    readonly targetGroup?: pulumi.Input<aws.lb.TargetGroup>;
}
```

So the previous code was type-safe and assumed that a targetGroup can be passed here. If we believe this is in error, then the type is likely still erroneous? Reading the codebase further, not one I'm very familiar with yet.

Comment (t0yv0) [reply awsx/ecs/containers.ts:104]: Ah.. I think I found it. 

There's a lot of object merging that ends to this line:

https://github.com/pulumi/pulumi-awsx/blob/master/awsx/ecs/ec2TaskDefinition.ts#L111

Looks like we pollute this with the targetGroup like you point out. 

https://github.com/pulumi/pulumi-awsx/blob/master/awsx/ecs/ec2TaskDefinition.ts#L84

https://github.com/pulumi/pulumi-awsx/blob/master/awsx/ecs/containers.ts#L82

Here we're extracting the port from the targetGroup:

https://github.com/pulumi/pulumi-awsx/blob/master/awsx/ecs/containers.ts#L69

And then passing to getMappingInputs.

So it's entirely safe to drop targetGroup here because https://github.com/pulumi/pulumi-awsx/blob/master/awsx/ecs/containers.ts#L82 builds a schema.TaskDefinitionContainerDefinitionInputs that does not need or have a targetGroup.

I think this is fine then!

I wish I knew how to take a JSON blob in TypeScript and drop out all the fields that are not specified in type T, that could be handy here.

TO our previous discussion, I think in most language other than TypeScript this provider has a serialization boundary and the serde framework accomplishes the same result, namely that schema-unlisted fields may drop out.

Comment (corymhall) [reply awsx/ecs/containers.ts:104]: I think the root cause of this is because the same types that are used as input types to the component are passed directly to the underlying resource, but those types don't actually match.

In the case of `TaskDefinitionPortMappingInputs`, this is the type that the user provides as an input to the component. We then use this same type as is and pass it to the [Port Mappings](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PortMapping.html) property on the container definition. This is what ends up causing the issue because the `TaskDefinitionPortMappingInputs` property doesn't exactly match the `PortMapping` property (the `targetGroup` property is the extra property). 

I think the ideal solution would be to create interfaces for the `containerDefinition` property (which is currently a JSON string) and then first convert these input properties to the containerDefinition property before stringifying it. I decided not to go down that route yet because ideally that would live in the aws classic provider.

Comment (corymhall) [reply awsx/ecs/containers.ts:104]: > TO our previous discussion, I think in most language other than TypeScript this provider has a serialization boundary and the serde framework accomplishes the same result, namely that schema-unlisted fields may drop out.

I'm not sure that would even catch this case because the schema property type is a `string` and we do pass a string, it just has extra properties.
