### PR TITLE
Fix getRegion functions

### LINKED ISSUE #1112: Timeout while waiting for state to become 'tfSTABLE' (last state: 'tfPENDING', timeout: 20m0s)
### What happened?

I'm receiving this error a lot when trying to test examples locally:

```

Diagnostics:
  pulumi:pulumi:Stack (ecs-node-p-it-antons-mac-nodejs-69324370):
    error: update failed

  aws:ecs:Service (my-service):
    error: 1 error occurred:
        * creating urn:pulumi:p-it-antons-mac-nodejs-69324370::ecs-node::awsx:ecs:FargateService$aws:ecs/service:Service::my-service: 1 error occurred:
        * waiting for ECS service (arn:aws:ecs:us-west-2:616138583583:service/cluster-e6c5e93/my-service-3c9c1de) to reach steady state after creation: timeout while waiting for state to become 'tfSTABLE' (last state: 'tfPENDING', timeout: 20m0s)

Outputs:
    url: "nginx-lb-f66cb5d-2145136225.us-west-2.elb.amazonaws.com"

Resources:
    + 33 created

Duration: 22m32s
```

This timeout happens when trying to record example baseline behavior, say for ecs/nodejs/ on AWS 5.42.0 and AWSX 1.x.x, but also when running examples on latest versions or the dependencies.  

I have seen this affect the aws:ecs/service:Service through FargateService and other component resource wrappers. 

For users affected by this issue, the current workaround per @danielrbradley is to apply a transformation that increases the custom timeout for the ECS service, see https://github.com/pulumi/pulumi-awsx/pull/1118 for a fully worked out example.

Please upvote this issue if this affects your workflow, and we can consider increasing default timeouts in the AWS provider.

### Example

N/A

### Output of `pulumi about`

```
CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Host     
OS       darwin
Version  14.0
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi
Token type     personal

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #1279: Run the ECS example, see error of https://logs.undefined.amazonaws.com/ preventing service up
### What happened?

I was trying [the ECS example](https://www.pulumi.com/docs/clouds/aws/guides/ecs/#creating-a-load-balanced-ecs-service).

The container service won't start properly. I saw error as:
```
Task stopped at: 2024-05-06T11:20:53.694Z
ResourceInitializationError: failed to validate logger args: create stream has been retried 7 times: failed to create Cloudwatch log stream: RequestError: send request failed caused by: Post "https://logs.undefined.amazonaws.com/": dial tcp: lookup logs.undefined.amazonaws.com on 172.31.0.2:53: no such host : exit status 1
```

Clearly this part of `https://logs.undefined.amazonaws.com/` isn't correct, since my region config is `us-west-2` and all resources were created there.

Tried to explicitly specify region as AI suggested, didn't work.
```Python
aws_provider = aws.Provider("aws_provider", region="us-west-2")
```

Was using the latest `pulumi-awsx==2.9.0` and `pulumi-aws==6.33.1`, downgraded to much earlier version, didn't work.

Unless I explicitly set log_group, as:
```Python
log_group = aws.cloudwatch.LogGroup("my-log-group")

# and this arg
log_configuration=awsx.ecs.TaskDefinitionLogConfigurationArgs(
    log_driver="awslogs",
    options={
        "awslogs-group": log_group.name,
        "awslogs-region": "us-west-2",  # Replace with your region
        "awslogs-stream-prefix": "ecs",
    },
),
```

This solved the issue finally.

### Example

```Python
import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx

lb = awsx.lb.ApplicationLoadBalancer("lb")
cluster = aws.ecs.Cluster("cluster")

service = awsx.ecs.FargateService("service",
    cluster=cluster.arn,
    assign_public_ip=True,
    desired_count=2,
    task_definition_args=awsx.ecs.FargateServiceTaskDefinitionArgs(
        container=awsx.ecs.TaskDefinitionContainerDefinitionArgs(
            name="my-service",
            image="nginx:latest",
            cpu=128,
            memory=512,
            essential=True,
            port_mappings=[awsx.ecs.TaskDefinitionPortMappingArgs(
                container_port=80,
                target_group=lb.default_target_group,
            )],
        ),
    ))

pulumi.export("url", pulumi.Output.concat("http://", lb.load_balancer.dns_name))
```

### Output of `pulumi about`

```
CLI
Version      3.115.1
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  python  unknown

Host
OS       darwin
Version  14.4.1
Arch     arm64

This project is written in python: executable='/Users/czhang/.asdf/shims/python3' version='3.11.8'

Current Stack: teng01/ecs/dev

TYPE                             URN
pulumi:pulumi:Stack              urn:pulumi:dev::ecs::pulumi:pulumi:Stack::ecs-dev
pulumi:providers:awsx            urn:pulumi:dev::ecs::pulumi:providers:awsx::default_2_7_0
pulumi:providers:aws             urn:pulumi:dev::ecs::pulumi:providers:aws::aws_provider
awsx:lb:ApplicationLoadBalancer  urn:pulumi:dev::ecs::awsx:lb:ApplicationLoadBalancer::lb
pulumi:providers:aws             urn:pulumi:dev::ecs::pulumi:providers:aws::default_6_0_4
aws:ecs/cluster:Cluster          urn:pulumi:dev::ecs::aws:ecs/cluster:Cluster::cluster


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/teng01
User           teng01
Organizations  teng01
Token type     personal

Dependencies:
NAME        VERSION
pip         24.0
setuptools  65.5.0
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by flostadler**
The `getRegion` functions were incorrectly trying to extract the current region from the provider. This silently resolved to undefined in certain cases; e.g. when no `AWS_REGION` ENV variable was set.
In particular this caused ECS tasks to fail because they used `https://logs.undefined.amazonaws.com/` as the endpoint for cloudwatch.

Instead we should use the `getRegion` data source to correctly identify the current region.

Fixes #1112
Fixes #1279

### CODE REVIEW

File: awsx/utils.ts [hunk 1]
```diff
@@ -82,15 +82,12 @@ export function getRegionFromOpts(opts: pulumi.CustomResourceOptions): pulumi.Ou
 
 /** @internal */
 export function getRegion(res: pulumi.Resource): pulumi.Output<aws.Region> {
-  // A little strange, but all we're doing is passing a fake type-token simply to get
-  // the AWS provider from this resource.
-  const provider = res.getProvider ? res.getProvider("aws::") : undefined;
-  return getRegionFromProvider(provider);
+  // uses the provider from the parent resource to fetch the region
+  return aws.getRegionOutput({}, { parent: res }).apply(region => region.name as aws.Region);
```
Comment (t0yv0) [inline awsx/utils.ts:86]: To confirm, as this inheritance is a little tricky, if `res` uses a custom version of the AWS provider, `{ parent: res}` will inherit that custom version so we get the right thing here?

File: awsx/s3/bucket.ts [hunk 2]
```diff
@@ -16,7 +16,7 @@ import * as aws from "@pulumi/aws";
 import * as pulumi from "@pulumi/pulumi";
 import { ResourceOptions } from "@pulumi/pulumi";
 import * as schema from "../schema-types";
-import { getRegion, getRegionFromOpts, parseArn } from "../utils";
```
Comment (t0yv0) [inline awsx/s3/bucket.ts:19]: Cleanup? Some missing liner rules?

File: awsx/utils.ts [hunk 3]
```diff
@@ -82,15 +82,12 @@ export function getRegionFromOpts(opts: pulumi.CustomResourceOptions): pulumi.Ou
...
 }
 
 function getRegionFromProvider(provider: pulumi.ProviderResource | undefined) {
```
Comment (t0yv0) [inline awsx/utils.ts:89]: Specify return type here please. I wonder what the "default" value was, aws.config.region. Now with this change it will pull the ambient AWS provider if provider=undefined, sounds like it's intended.

**Review by t0yv0 — APPROVED** [review]

File: awsx/utils.ts (hunk 1 above)
Comment (flostadler) [reply awsx/utils.ts]: Yes, that's my understanding. It actually retrieves the provider configured for the parent. If that one's using a custom version then this will also use that version.

File: awsx/s3/bucket.ts (hunk 2 above)
Comment (flostadler) [reply awsx/s3/bucket.ts:19]: Yeah, I'm currently trying to see which one we're missing

File: awsx/utils.ts (hunk 1 above)
Comment (t0yv0) [reply awsx/utils.ts]: I see this is already shipped in aws-apigateway so that's nice! THank you.
