### PR TITLE
testing: examples/ecs/nodejs add missing dependsOn

### LINKED ISSUE #1418: Flaky TestAccEcsCapacityProviderService
Failed with:

```
    aws:ecs:Service (my-service):
      error:   sdk-v2/provider2.go:520: sdk.helper_schema: creating ECS Service (my-service-9669d07): operation error ECS: CreateService, https response error StatusCode: 400, RequestID: 187a5383-55d4-4df4-b185-0f69370c60cf, InvalidParameterException: The target group with targetGroupArn arn:aws:elasticloadbalancing:us-west-2:894850187425:targetgroup/nginx-lb-111793d/91d31eae55038f3a does not have an associated load balancer.: provider=aws@6.57.0
      error: 1 error occurred:
      	* creating ECS Service (my-service-9669d07): operation error ECS: CreateService, https response error StatusCode: 400, RequestID: 187a5383-55d4-4df4-b185-0f69370c60cf, InvalidParameterException: The target group with targetGroupArn arn:aws:elasticloadbalancing:us-west-2:894850187425:targetgroup/nginx-lb-111793d/91d31eae55038f3a does not have an associated load balancer.

```

But restarting CI fixed the test.

### PR DESCRIPTION
**Pull request by t0yv0**
Pulumi was not recognizing that the underlying aws.ecs.Service should wait for the load balancer to be provisioned, causing a race that sporadically would flake up the test. This is now compensated by with a dependsOn option.

Fixes #1418

### CODE REVIEW

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-awsx/issues/1442 marking another test as a flaky test.

File: examples/ecs/nodejs/index.ts [hunk 1]
```diff
@@ -29,6 +29,8 @@ const service = new ecs.FargateService("my-service", {
         subnets: vpc.publicSubnetIds,
         assignPublicIp: true,
     },
+}, {
+    dependsOn: [lb.loadBalancer],
```
Comment (corymhall) [inline examples/ecs/nodejs/index.ts:33]: Should we add logic to the `FargateService` component to automatically add the dependency on the load balancer?

**Review by corymhall — APPROVED** [review]

File: examples/ecs/nodejs/index.ts (hunk 1 above)
Comment (t0yv0) [reply examples/ecs/nodejs/index.ts:33]: Based on our conversation I think we concluded given the component is under the classic portion of the provider our preference would be to sanitize examples instead to not rely on those components.
